version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/hitalent
      - PYTHONPATH=/app/src
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./alembic.ini:/app/alembic.ini

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hitalent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hitalent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data: